# Generated by Django 5.0.7 on 2024-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friendship_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.IntegerField(default=0),
        ),
    ]
